name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"

      - name: Setup Python Virtual Environment
        run: python -m venv venv

      - name: Install Dependencies
        run: venv/bin/pip install -r requirements.txt

      - name: Instal LaTeX distribution
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-xetex
          sudo apt-get clean

      - name: Run Tests
        run: |
          cd src
          venv/bin/python -m unittest -v
